"use client"

import { useState, type CSSProperties } from "react"
import { ArrowUpRight, Search, X, Check, Terminal, Activity } from "lucide-react"
import { products, type Product } from "./products"
import ProductIcon from "./product-icon"

const categories = ["All products", "Cloud & AI", "Developer tools", "Commerce", "More from us"]

function ProductVisual({ product }: { product: Product }) {
  if (product.id === "cloudploy") return <div className="product-visual visual-cloud" aria-hidden="true"><div className="mini-terminal"><div className="terminal-header"><span><i /><i /><i /></span><span>your next deployment</span><Terminal size={12} /></div><div className="terminal-body"><span className="terminal-muted">~/my-next-big-thing</span><p><span className="terminal-blue">❯</span> deploy with cloudploy<span className="terminal-cursor">▌</span></p><span className="terminal-line"><Check size={12} /> Connected to your cloud</span><span className="terminal-line"><Check size={12} /> Built for your workflow</span><div className="deploy-pill"><span className="status-dot" /> From prompt to production <ArrowUpRight size={12} /></div></div></div><span className="visual-caption mono">YOUR CLOUD. YOUR WORKFLOW.</span></div>
  if (product.id === "skaleagents") return <div className="product-visual visual-agents" aria-hidden="true"><div className="agent-connector connector-one" /><div className="agent-connector connector-two" /><div className="agent-connector connector-three" /><span className="agent-hub"><ProductIcon id="skaleagents" size={35} /></span><span className="agent-chip agent-chip-one"><span className="small-icon">⌘</span> Your editor</span><span className="agent-chip agent-chip-two"><span className="status-dot" /> Security review</span><span className="agent-chip agent-chip-three"><Activity size={14} /> Reliability</span><span className="visual-caption mono">SPECIALIST AGENTS. SHARED CONTEXT.</span></div>
  if (product.id === "crontinel") return <div className="product-visual visual-monitor" aria-hidden="true"><div className="monitor-card"><div className="monitor-header"><Activity size={17} /><span>Inside your application</span><span className="monitor-badge">DEMO</span></div>{["Scheduled jobs", "Queue workers", "Agent runs"].map((label, index) => <div className="monitor-row" key={label}><span>{label}</span><div className="heartbeat-bars">{Array.from({ length: 18 }, (_, i) => <i key={i} style={{ height: `${8 + ((i * 7 + index * 13) % 22)}px` }} />)}</div><span className="monitor-check"><Check size={12} /></span></div>)}</div><span className="visual-caption mono">VISIBILITY BEYOND THE UPTIME CHECK.</span></div>
  if (product.id === "toolblip") return <div className="product-visual visual-tools" aria-hidden="true"><div className="tool-tiles">{["{ }", "Aa", "#", "↔", "</>", "◐"].map((symbol, i) => <span key={symbol} className={`tool-tile tile-${i}`}>{symbol}</span>)}</div><span className="visual-caption mono">OPEN A TAB. GET IT DONE.</span></div>
  return <div className={`product-visual visual-symbol visual-${product.id}`} aria-hidden="true"><div className="symbol-orbit" /><span className="product-large-symbol"><ProductIcon id={product.id} size={66} /></span><span className="symbol-small">{product.id === "amazingplugins" ? "Made for WooCommerce" : product.id === "appnary" ? "Made for Shopify" : product.id === "harun" ? "Notes from the work" : "From the lab"}</span><span className="visual-caption mono">{product.tags.join(" / ").toUpperCase()}</span></div>
}

export default function ProductShowcase({ searchable = false }: { searchable?: boolean }) {
  const [category, setCategory] = useState("All products")
  const [query, setQuery] = useState("")
  const filtered = products.filter(product => (category === "All products" || category === product.category) && `${product.name} ${product.description} ${product.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase().trim()))

  return <div className="product-showcase">
    <div className="product-toolbar"><div className="product-filters" role="group" aria-label="Filter products by category">{categories.map(item => <button key={item} aria-pressed={item === category} onClick={() => setCategory(item)} className={item === category ? "active" : ""}>{item}{item === "All products" && <span>{products.length.toString().padStart(2, "0")}</span>}</button>)}</div>{searchable && <div className="product-search"><Search size={16} /><input type="search" aria-label="Search products" value={query} onChange={event => setQuery(event.target.value)} placeholder="Find your next tool…" />{query && <button aria-label="Clear search" onClick={() => setQuery("")}><X size={15} /></button>}</div>}</div>
    <span className="sr-only" role="status">{filtered.length} {filtered.length === 1 ? "product" : "products"} shown</span>
    <div className="product-grid">{filtered.map(product => <article key={product.id} className="product-card" style={{ "--product-color": product.color, "--product-background": product.background } as CSSProperties}><a className="product-card-link" href={product.url} target="_blank" rel="noreferrer" aria-label={`Explore ${product.name} (opens in a new tab)`}><div className="product-art"><div className="product-art-top"><span>{product.category}</span>{product.status && <span className="product-status"><span />{product.status}</span>}</div><ProductVisual product={product} /></div><div className="product-card-body"><div className="product-title"><span className="product-logo"><ProductIcon id={product.id} size={22} /></span><h3>{product.name}</h3><span className="product-arrow"><ArrowUpRight size={20} /></span></div><h4>{product.tagline}</h4><p>{product.description}</p><div className="product-card-bottom"><span>{product.url.replace("https://", "")}</span><span>Explore <ArrowUpRight size={13} /></span></div></div></a></article>)}</div>
    {filtered.length === 0 && <div className="empty-products"><Search size={28} /><h3>No products found.</h3><p>Try a different search or explore the full collection.</p><button className="button button-dark" onClick={() => { setCategory("All products"); setQuery("") }}>Show all products</button></div>}
    <div className="product-endnote"><span><span className="status-dot" /> Built here. Always evolving.</span><span className="mono">{filtered.length.toString().padStart(2, "0")} PROJECTS / ONE CURIOUS STUDIO</span></div>
  </div>
}
